name: 'Amazon App Runner "Deploy Service" Action for GitHub Actions'
description: 'Registers and deploys the application as App Runner service'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  service:
    description: 'The name of the App Runner service'
    required: true
  source-connection-arn:
    description: 'ARN for the `GitHubConnection` in App Runner'
    required: false
  access-role-arn:
    description: 'ARN for IAM Role, if the App Runner service is configured with ECR image'
    required: false
  repo:
    description: "GitHub source repository URL"
    required: false
  branch:
    description: "Repository branch name"
    required: false
  image:
    description: 'Docker image URI with tag'
    required: false
  runtime:
    description: 'Runtime of the application, note: AppRunner only supports `NODEJS_12` and `PYTHON_3` runtime types'
    required: false
  build-command:
    description: "Application build command"
    required: false
  start-command:
    description: "Application start command"
    required: false
  port:
    description: "The service uses this TCP port"
    required: false
  region:
    description: "AWS deployment region"
    required: false
  cpu:
    description: 'CPU for the service, defaults to 1 vCPU'
    required: false
  memory:
    description: 'Memory for the service, defaults to 2 GB'
    required: false
  healthCheckProtocol:
    description: 'The IP protocol that App Runner uses to perform health checks for your service, possible values are TCP or HTTP, defaults to TCP'
    required: false
  healthCheckPath:
    description: 'The URL that health check requests are sent to (only for HTTP based checks), defaults to /'
    required: false
  healthCheckInterval:
    description: 'The time interval, in seconds, between health checks, defaults to 5'
    required: false
  healthCheckTimeout:
    description: 'The time, in seconds, to wait for a health check response before deciding it failed, defaults to 2'
    required: false
  healthCheckHealthyThreshold:
    description: 'The number of consecutive checks that must succeed before App Runner decides that the service is healthy, defaults to 1'
    required: false
  healthCheckUnhealthyThreshold:
    description: 'The number of consecutive checks that must fail before App Runner decides that the service is unhealthy, defaults to 5'
    required: false
  wait-for-service-stability:
    description: 'Whether to wait for the App Runner service to reach stable state after deploying the new task definition. Valid value is "true". Will default to not waiting.'
    required: false
outputs:
  service-id:
    description: 'App Runner service ID'
runs:
  using: 'node12'
  main: 'dist/index.js'
